version: '2'
services:
    jhphotobird-app:
        image: jhphotobird
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhphotobird-postgresql:5432/jhPhotoBird
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhphotobird-elasticsearch:9300
        ports:
            - 8080:8080
    jhphotobird-postgresql:
        extends:
            file: postgresql.yml
            service: jhphotobird-postgresql
    jhphotobird-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhphotobird-elasticsearch
